[package]
name = "shared"
description = "Shared objects for libcontainer"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.215", features = ["derive"] }
zbus = { version = "5.1.1", default-features = false }

[dev-dependencies]
serde_json = "1.0.133"
