name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: extractions/setup-just@v2
    - uses: actions/checkout@v4
    - name: Build
      run: just build-rust-debug
    - name: Run tests
      run: just test-rust
